### ISSUE TITLE
Fix collocate threshold

### ISSUE THREAD

**Issue by fredrik1984** [welfare-state-analytics/welfare_state_analytics#99]
```log
% concept_cooccurrence --concept=propaganda --context-width=4 --partition-key=year  \
>       --pos-includes='|NN|' --lemmatize --min-word-length=2 \
>       --filename-field='year:prot\_(\d{4}).*' --no-concept \
>       --count-threshold=10 riksdagens-protokoll.1920-2019.sparv4.csv.zip propaganda_4_NN.zip

Traceback (most recent call last):
  File "/Users/frno0044/Library/Caches/pypoetry/virtualenvs/concept-coocurrence-79nef9cn-py3.8/lib/python3.8/site-packages/pandas/core/groupby/generic.py", line 1418, in _transform_general
    path, res = self._choose_path(fast_path, slow_path, group)
  File "/Users/frno0044/Library/Caches/pypoetry/virtualenvs/concept-coocurrence-79nef9cn-py3.8/lib/python3.8/site-packages/pandas/core/groupby/generic.py", line 1528, in _choose_path
    res = slow_path(group)
  File "/Users/frno0044/Library/Caches/pypoetry/virtualenvs/concept-coocurrence-79nef9cn-py3.8/lib/python3.8/site-packages/pandas/core/groupby/generic.py", line 1516, in <lambda>
    slow_path = lambda group: group.apply(
  File "/Users/frno0044/Library/Caches/pypoetry/virtualenvs/concept-coocurrence-79nef9cn-py3.8/lib/python3.8/site-packages/pandas/core/frame.py", line 7548, in apply
    return op.get_result()
  File "/Users/frno0044/Library/Caches/pypoetry/virtualenvs/concept-coocurrence-79nef9cn-py3.8/lib/python3.8/site-packages/pandas/core/apply.py", line 180, in get_result
    return self.apply_standard()
  File "/Users/frno0044/Library/Caches/pypoetry/virtualenvs/concept-coocurrence-79nef9cn-py3.8/lib/python3.8/site-packages/pandas/core/apply.py", line 271, in apply_standard
    results, res_index = self.apply_series_generator()
  File "/Users/frno0044/Library/Caches/pypoetry/virtualenvs/concept-coocurrence-79nef9cn-py3.8/lib/python3.8/site-packages/pandas/core/apply.py", line 300, in apply_series_generator
    results[i] = self.f(v)
  File "/Users/frno0044/Library/Caches/pypoetry/virtualenvs/concept-coocurrence-79nef9cn-py3.8/lib/python3.8/site-packages/pandas/core/groupby/generic.py", line 1517, in <lambda>
    lambda x: getattr(x, func)(*args, **kwargs), axis=self.axis
TypeError: 'int' object is not callable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/frno0044/Library/Caches/pypoetry/virtualenvs/concept-coocurrence-79nef9cn-py3.8/bin/concept_cooccurrence", line 8, in <module>
    sys.exit(main())
  File "/Users/frno0044/Library/Caches/pypoetry/virtualenvs/concept-coocurrence-79nef9cn-py3.8/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/frno0044/Library/Caches/pypoetry/virtualenvs/concept-coocurrence-79nef9cn-py3.8/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/frno0044/Library/Caches/pypoetry/virtualenvs/concept-coocurrence-79nef9cn-py3.8/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/frno0044/Library/Caches/pypoetry/virtualenvs/concept-coocurrence-79nef9cn-py3.8/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/frno0044/Library/Caches/pypoetry/virtualenvs/concept-coocurrence-79nef9cn-py3.8/lib/python3.8/site-packages/penelope/scripts/concept_co_occurrence.py", line 79, in main
    cli_concept_co_occurrence(
  File "/Users/frno0044/Library/Caches/pypoetry/virtualenvs/concept-coocurrence-79nef9cn-py3.8/lib/python3.8/site-packages/penelope/scripts/concept_co_occurrence.py", line 168, in cli_concept_co_occurrence
    co_occurrence.compute_and_store(
  File "/Users/frno0044/Library/Caches/pypoetry/virtualenvs/concept-coocurrence-79nef9cn-py3.8/lib/python3.8/site-packages/penelope/co_occurrence/windows_co_occurrence.py", line 203, in compute_and_store
    coo_df = partitioned_corpus_concept_co_occurrence(
  File "/Users/frno0044/Library/Caches/pypoetry/virtualenvs/concept-coocurrence-79nef9cn-py3.8/lib/python3.8/site-packages/penelope/co_occurrence/windows_co_occurrence.py", line 181, in partitioned_corpus_concept_co_occurrence
    df_total = df_total[df_total.groupby(["w1", "w2"]).transform('size') > count_threshold]
  File "/Users/frno0044/Library/Caches/pypoetry/virtualenvs/concept-coocurrence-79nef9cn-py3.8/lib/python3.8/site-packages/pandas/core/groupby/generic.py", line 1491, in transform
    return self._transform_general(
  File "/Users/frno0044/Library/Caches/pypoetry/virtualenvs/concept-coocurrence-79nef9cn-py3.8/lib/python3.8/site-packages/pandas/core/groupby/generic.py", line 1420, in _transform_general
    return self._transform_item_by_item(obj, fast_path)
  File "/Users/frno0044/Library/Caches/pypoetry/virtualenvs/concept-coocurrence-79nef9cn-py3.8/lib/python3.8/site-packages/pandas/core/groupby/generic.py", line 1567, in _transform_item_by_item
    raise TypeError("Transform function invalid for data types")
TypeError: Transform function invalid for data types
```

**Comment by roger-mahler** [comment]
Fixed in release 0.2.2.
